apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dyik936qw-go 
  janus-idp.io/tekton: dyik936qw-go
  backstage.io/kubernetes-id: dyik936qw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dyik936qw-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  